// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simflu6
List simflu6(List para, bool verbose, String postfix);
RcppExport SEXP SimFlu6_simflu6(SEXP paraSEXP, SEXP verboseSEXP, SEXP postfixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type para(paraSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< String >::type postfix(postfixSEXP);
    rcpp_result_gen = Rcpp::wrap(simflu6(para, verbose, postfix));
    return rcpp_result_gen;
END_RCPP
}
