# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simflu6 <- function(para, verbose = TRUE, postfix = "") {
    .Call('SimFlu6_simflu6', PACKAGE = 'SimFlu6', para, verbose, postfix)
}

