readFLUVEE = function(filename)
{
  para <- list()
  Y <- readLines(filename)
  para$title <- strsplit(Y[grep("Title",Y)],',')[[1]][2]
  para$months <- as.numeric(strsplit(Y[grep("Number of months in the study",Y)],',')[[1]][2])
  para$strata <- as.numeric(strsplit(Y[grep("Number of strata",Y)],',')[[1]][2])
  para$size_strata <- as.numeric(strsplit(Y[grep("Sizes of strata",Y)],',')[[1]][2:(1+para$strata)])
  para$num_infected_persons <- as.numeric(strsplit(Y[grep("Initial number of infected persons",Y)],',')[[1]][2])
  para$prob_condition_strata <- matrix(t(sapply(0:2, function(i) as.numeric(strsplit(Y[grep("Probability of X=1",Y)+i],',')[[1]][2:(1+para$strata)]))),nrow=3,ncol=para$strata)
  para$vac_inc_coverage <- matrix(t(sapply(1:(para$months+1), function(i) as.numeric(strsplit(Y[(grep("Vaccination incremental coverage for X=1, U=1",Y)+i)],',')[[1]][2:(1+para$strata)]))),nrow=para$months+1,ncol=para$strata)
  para$vac_multiplyer <- matrix(t(sapply(0:1, function(i) as.numeric(strsplit(Y[grep("Vaccination incremental coverage multiplier for X=0",Y)+i],',')[[1]][2:(1+para$strata)]))),nrow=2)
  para$contacts_per_day <- as.numeric(strsplit(Y[grep("Number of contacts per day for each person",Y)],',')[[1]][2:(1+para$strata)])
  para$dist_contacts <- matrix(t(sapply(1:2, function(i) as.numeric(strsplit(Y[grep("Distribution of contacts - K by K matrix",Y)+i],',')[[1]][2:(1+para$strata)]))),nrow = para$strata)
  para$latency_days <- as.numeric(strsplit(Y[grep("Length of latent period",Y)],',')[[1]][2:(1+para$strata)])
  para$infectious_days <- as.numeric(strsplit(Y[grep("Length of infectious period",Y)],',')[[1]][2:(1+para$strata)])
  para$prob_illness <- as.numeric(strsplit(Y[grep("Probability of illness given infection",Y)],',')[[1]][2:(1+para$strata)])
  para$relative_infectious_not_ill <- as.numeric(strsplit(Y[grep("Relative infectiousness if not ill",Y)],',')[[1]][2:(1+para$strata)])
  para$prob_transmission <- matrix(t(sapply(1:para$months, function(i) as.numeric(strsplit(Y[(grep("Transmission probabilities to unprotected for X=1",Y)+i)],',')[[1]][2:(1+para$strata)]))),nrow=para$months)
  para$trans_prob_multiplier <- as.numeric(strsplit(Y[grep("Transmission probabilities multipliers for X=0 in unvaccinated or unprotected",Y)],',')[[1]][2:(1+para$strata)])
  para$prob_transmission_vac <- matrix(t(sapply(1:para$months, function(i) as.numeric(strsplit(Y[(grep("Vaccine efficacy for X=1",Y)+i)],',')[[1]][2:(1+para$strata)]))),nrow = para$months)
  para$vec_efficacy_multiplier <- as.numeric(strsplit(Y[grep("Vaccine efficacy multipliers for X=0",Y)],',')[[1]][2:(1+para$strata)])
  para$length_ARI <- as.numeric(strsplit(Y[grep("Length of NFARI episode",Y)],',')[[1]][2:(1+para$strata)])
  para$daily_prob_NFARI <- matrix(t(sapply(1:para$months, function(i) as.numeric(strsplit(Y[(grep("Daily probabilities of onset of NFARI for X=1 in unvaccinated or unprotected persons",Y)+i)],',')[[1]][2:(1+para$strata)]))),nrow = para$months)
  para$probARI_vaccined_multiplier <- as.numeric(strsplit(Y[grep("NFARI probabilities multipliers for vaccinated or protected persons",Y)],',')[[1]][2:(1+para$strata)])
  para$probARI_X0_multiplier <- as.numeric(strsplit(Y[grep("NFARI probabilities multipliers for X=0",Y)],',')[[1]][2:(1+para$strata)])
  para$prob_visit_FARI <- as.numeric(strsplit(Y[grep("For unvaccinated or unprotected with X=1 and U=1",Y)],',')[[1]][2:(1+para$strata)])
  para$visit_FARI_multiplier <- matrix(t(sapply(0:2, function(i) as.numeric(strsplit(Y[(grep("Multiplier for vaccinated",Y)+i)],',')[[1]][2:(1+para$strata)]))),nrow=3)
  para$prob_visit_NFARI <- as.numeric(strsplit(Y[grep("Probability of visit for a case of NFARI:",Y)+1],',')[[1]][2:(1+para$strata)])
  para$visit_NFARI_multiplier <- matrix(t(sapply(2:4, function(i) as.numeric(strsplit(Y[(grep("Probability of visit for a case of NFARI:",Y)+i)],',')[[1]][2:(1+para$strata)]))),nrow=3)
  para$all_or_no_vaccine <- ifelse(strsplit(Y[grep("All-or-none vaccine",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$sim <- as.numeric(strsplit(Y[grep("Number of simulations",Y)],',')[[1]][2])
  para$rseed <- as.numeric(strsplit(Y[grep("Seed",Y)],',')[[1]][2])
  para$begin_year <- as.numeric(strsplit(Y[grep("Year of beginning of study",Y)],',')[[1]][2])
  para$begin_month <- as.numeric(strsplit(Y[grep("Month of beginning of study",Y)],',')[[1]][2])
  para$inputsfile <- ifelse(strsplit(Y[grep("Input and calculated parameters",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$vaccination_file <- ifelse(strsplit(Y[grep("Vaccination",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$detailed_file <- ifelse(strsplit(Y[grep("Detailed",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$contacts_file <- ifelse(strsplit(Y[grep("Contacts",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$prevalance_file <- ifelse(strsplit(Y[grep("Prevalence",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$daily_each_sim_file <- ifelse(strsplit(Y[grep("Incidence-daily each simulation",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$monthly_each_sim_file <- ifelse(strsplit(Y[grep("Incidence-monthly each simulation",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$seasonal_each_sim_file <- ifelse(strsplit(Y[grep("Incidence-season each simulation",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$daily_overall_file <- ifelse(strsplit(Y[grep("Incidence-daily overall",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$monthly_overall_file <- ifelse(strsplit(Y[grep("Incidence-monthly overall",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$seasonal_overall_file <- ifelse(strsplit(Y[grep("Incidence-season overall",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$population_report_file <- ifelse(strsplit(Y[grep("Outcomes file",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  para$timestamp <- ifelse(strsplit(Y[grep("Add timestamp to output file names",Y)],',')[[1]][2]=="yes",TRUE,FALSE)
  return(para)
}
